version: '3'
services:
  ryu:
    image: joagonzalez/ryu-controller:1.0.0
    build:
      context: ryu/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '6633:6633'
      - '6653:6653'
    expose:
      - '8080'
      - '6633'
      - '6653'
    networks:
      app_net:
        ipv4_address: 172.18.0.10

  call_admission_control_frontend:
    image: joagonzalez/cac-frontend:1.0.0
    build:
      context: call-admission-control/src/frontend/
      dockerfile: Dockerfile
    expose:
      - '3000'
    ports:
      - '3000:3000'
    networks:
      app_net:
        ipv4_address: 172.18.0.12
    volumes:
      - ./call-admission-control/src/frontend/src/index.html:/app/src/index.html

  call_admission_control_backend:
    image: joagonzalez/cac-backend:1.0.0
    build:
      context: call-admission-control/src/backend/
      dockerfile: Dockerfile
    expose:
      - '8000'
      - '9999'
    ports:
      - '8000:8000'
      - '9999:9999'
    depends_on:
      - call_admission_control_frontend
      - asterisk
      - ryu
    networks:
      app_net:
        ipv4_address: 172.18.0.13

  # asterisk:
  #   image: joagonzalez/asterisk-ari:1.0.0
  #   build:
  #     context: asterisk/
  #     dockerfile: Dockerfile
  #   expose:
  #     - '8088'
  #   ports:
  #     - '8088:8088'
  #   depends_on:
  #     - ryu
  #   networks:
  #     app_net:
  #       ipv4_address: 172.18.0.11
  #   volumes:
  #     - ./asterisk/conf/sip.conf:/etc/asterisk/sip.conf
  #     - ./asterisk/conf/extensions.conf:/etc/asterisk/extensions.conf
  #     - ./asterisk/conf/ari.conf:/etc/asterisk/ari.conf

  # mininet:
  #   image: joagonzalez/cac-mininet:1.0.0
  #   ports:
  #     - '6632:6632'
  #   expose:
  #     - '6632'
  #   networks:
  #     app_net:
  #       ipv4_address: 172.18.0.14
  #   build:
  #     context: mininet/
  #     dockerfile: Dockerfile
  #   tty: true
  #   privileged: true
  #   depends_on:
  #     - ryu

  # simulation:
  #   image: joagonzalez/cac-simulation-caller:1.0.0
  #   networks:
  #     app_net:
  #       ipv4_address: 172.18.0.15
  #   build:
  #     context: simulation/
  #     dockerfile: Dockerfile
  #   tty: true
  #   privileged: true
  #   depends_on:
  #     - asterisk
  #     - ryu
  #     - call_admission_control_backend
      
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24